export const XLink =  "https://x.com/"
export const LinkedInLink =  "https://www.linkedin.com/in/ghoshprobal/"
export const GithUbLink =  "https://github.com/prodot-com"
export const ResumeLink =  "https://drive.google.com/file/d/1H7RGdD3meBd-95SSqCbs25iD_Xo-fKyP/view?usp=sharing"
export const MailLink = "https://mail.google.com/mail/?view=cm&fs=1&to=xprobal52@gmail.com"