import type { Metadata } from "next";
import { Instrument_Serif, Kablammo } from "next/font/google";
import "./globals.css";
import { BottomDock } from "@/components/BottomDock";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";
import { ScrollProgress } from "@/components/ui/scroll-progress";
import { Toaster } from "sonner";
import ScrollToTopOnLoad from "@/components/ScrollToponLoad";

config.autoAddCss = false;

const instrumentSerif = Instrument_Serif({
  weight: "400",
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--font-instrument-serif",
  display: "swap",
});

const kablammo = Kablammo({
  subsets: ["latin"],
  variable: "--font-kablammo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${instrumentSerif.variable} ${kablammo.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ScrollToTopOnLoad/>
          <Toaster />
          <Navbar />
          <ScrollProgress className="fixed left-0 w-full h-[5px] transition-all duration-300" />
          {children}
          <BottomDock />
        </ThemeProvider>
      </body>
    </html>
  );
}
